spring:
  application:
    name: bookshelf
  datasource:
    url: ${BOOKSHELF_DB_URL:jdbc:mariadb://${BOOKSHELF_DB_HOST:${DB_HOST:localhost}}:${BOOKSHELF_DB_PORT:${DB_PORT:3306}}/${BOOKSHELF_DB_DATABASE:${DB_DATABASE:bookshelf}}?characterEncoding=UTF-8}
    username: ${BOOKSHELF_DB_USERNAME:${DB_USERNAME:bookshelf}}
    password: ${BOOKSHELF_DB_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false

app:
  db:
    enabled: ${APP_DB_ENABLED:true}
  registration:
    enabled: ${REGISTRATION:${APP_REGISTRATION_ENABLED:false}}

server:
  port: ${SERVER_PORT:25647}
