spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-163-34-107.compute-1.amazonaws.com:5432/d67ivivnl469s5
    username: snzjhcnrpzgzrh
    password: 4959edb04b87fd8cfca029ffd1ad73ff48c15557ba3bf7deb248d4b9e584194b
  sql:
    init:
      platform: postgres

mybatis:
  mapper-locations: classpath:mapper/**/*.xml